.TH ttybattle 1 "January 5, 2017"
.SH NAME
ttybattle \- Turn-based terminal game.
.PP
.SH SYNOPSIS
ttybattle
.PP
.SH DESCRIPTION
Game for the terminal. Turn-based battle against the AI.
.PP
.SH How-to
Simple menu-style control with arrow keys and Enter to make your choices throughout the game. ESC quits the game instantly.
.PP
.SH BUGS
No known.
.PP
.SH AUTHOR
schnitz (https://github.com/schnitz81)
